# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kadai21ForRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kadai21ForRxSwift

  target 'Kadai21ForRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kadai21ForRxSwiftUITests' do
    # Pods for testing
  end

end
