# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kadai21ForRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kadai21ForRxSwift
	pod 'RealmSwift', '5.3.6'
	pod 'RxSwift', '5.1.1'
	pod 'RxCocoa', '5.1.1'
	pod 'RxDataSources', '4.0.1'


  target 'Kadai21ForRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kadai21ForRxSwiftUITests' do
    # Pods for testing
  end

end
